In [1]:
import pandas as pd

In [2]:
mvps = pd.read_csv("mvps.csv")

In [3]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,15,16,Bernard King,34,WSB,0.0,7.0,960,0.007,64,...,5.0,4.6,0.9,0.3,0.472,0.216,0.790,3.5,0.070,2022
636,16,17,Kenny Smith,25,HOU,0.0,5.0,960,0.005,78,...,2.1,7.1,1.4,0.1,0.520,0.363,0.844,9.0,0.161,2022
637,17,18,Hakeem Olajuwon,28,HOU,0.0,4.0,960,0.004,56,...,13.8,2.3,2.2,3.9,0.508,0.000,0.769,8.6,0.201,2022
638,18,19T,Tim Hardaway,24,GSW,0.0,1.0,960,0.001,82,...,4.0,9.7,2.6,0.1,0.476,0.385,0.803,9.9,0.148,2022
639,19,19T,Kevin McHale,33,BOS,0.0,1.0,960,0.001,68,...,7.1,1.9,0.4,2.1,0.553,0.405,0.829,7.9,0.182,2022

In [4]:
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [5]:
mvps

              Player  Year  Pts Won  Pts Max  Share
0     Michael Jordan  1991    891.0      960  0.928
1      Magic Johnson  1991    497.0      960  0.518
2     David Robinson  1991    476.0      960  0.496
3    Charles Barkley  1991    222.0      960  0.231
4        Karl Malone  1991    142.0      960  0.148
..               ...   ...      ...      ...    ...
635     Bernard King  2022      7.0      960  0.007
636      Kenny Smith  2022      5.0      960  0.005
637  Hakeem Olajuwon  2022      4.0      960  0.004
638     Tim Hardaway  2022      1.0      960  0.001
639     Kevin McHale  2022      1.0      960  0.001

[640 rows x 5 columns]

In [7]:
players = pd.read_csv("players.csv")

In [8]:
players

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18880,836,601,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
18881,837,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
18882,838,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
18883,839,604,Cody Zeller,C,29,POR,27,0,13.1,1.9,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
18884,840,605,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [12]:
del players["Unnamed: 0"]
del players["Rk"]

In [13]:
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18880,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,5.5,.465,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
18881,Trae Young,PG,23,ATL,76,76,34.9,9.4,20.3,.460,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
18882,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,4.4,.526,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
18883,Cody Zeller,C,29,POR,27,0,13.1,1.9,3.3,.567,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
18884,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,6.5,.626,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [14]:
players["Player"].head(50)

0         Alaa Abdelnaby
1     Mahmoud Abdul-Rauf
2             Mark Acres
3          Michael Adams
4           Mark Aguirre
5            Danny Ainge
6            Mark Alarie
7           Steve Alford
8          Greg Anderson
9          Greg Anderson
10         Greg Anderson
11         Greg Anderson
12         Nick Anderson
13          Ron Anderson
14       Willie Anderson
15        Michael Ansley
16        B.J. Armstrong
17         Vincent Askew
18          Keith Askins
19           MiloÅ¡ BabiÄ‡
20          Thurl Bailey
21           Cedric Ball
22         Ken Bannister
23      Charles Barkley*
24           Dana Barros
25           John Battle
26          Kenny Battle
27          Kenny Battle
28          Kenny Battle
29       William Bedford
30       Benoit Benjamin
31       Benoit Benjamin
32       Benoit Benjamin
33       Winston Bennett
34           Larry Bird*
35      Rolando Blackman
36          Lance Blanks
37       Mookie Blaylock
38         Muggsy Bogues
39            Manute Bol
40        Anthony Bonner
41             Sam Bowie
42          Randy Breuer
43      Frank Brickowski
44          Scott Brooks
45          Chucky Brown
46             Dee Brown
47                Player
48            Mike Brown
49            Tony Brown
Name: Player, dtype: object

In [20]:
players["Player"] = players["Player"].str.replace("*", "", regex = False)

In [22]:
player.groupby(["Player", "Year"])

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,8,9,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,9,9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,10,9,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,11,9,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991

In [23]:
def single_row(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row
players = player.groupby(["Player", "Year"]).apply(single_row)

In [41]:
del players["Unnamed: 0"]
del players["Rk"]

In [43]:
players.head(20)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
164,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
633,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1092,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1579,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
2067,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995
2563,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,2.0,4.7,6.8,0.9,0.5,0.3,1.0,1.7,7.5,1996
3138,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,.483,...,2.7,5.2,7.9,0.8,0.8,0.2,0.9,1.7,7.2,1997
3725,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,.453,...,2.7,5.5,8.1,1.5,1.0,0.3,0.8,1.9,7.3,1998
4283,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,.422,...,1.6,2.9,4.6,0.5,0.6,0.2,0.4,1.4,4.9,1999
4811,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,.447,...,2.0,4.0,5.9,1.0,0.6,0.2,0.6,1.5,5.0,2000
5330,A.C. Green,PF,37,MIA,82,1,17.2,1.8,4.0,.444,...,1.3,2.5,3.8,0.5,0.4,0.1,0.5,1.5,4.5,2001
4684,A.J. Bramlett,C,23,CLE,8,0,7.6,0.5,2.6,.190,...,1.5,1.3,2.8,0.0,0.1,0.0,0.4,1.6,1.0,2000
127,A.J. English,SG,23,WSB,70,12,20.6,3.6,8.2,.439,...,0.9,1.2,2.1,2.5,0.4,0.2,1.6,1.8,8.8,1991
597,A.J. English,SG,24,WSB,81,6,20.6,4.5,10.4,.433,...,0.9,1.2,2.1,1.8,0.4,0.1,1.1,2.0,10.9,1992
5333,A.J. Guyton,PG,22,CHI,33,8,19.1,2.4,5.8,.406,...,0.3,0.8,1.1,1.9,0.3,0.2,0.7,1.1,6.0,2001
5886,A.J. Guyton,PG,23,CHI,45,6,13.5,2.0,5.4,.361,...,0.3,0.7,1.0,1.8,0.2,0.2,0.8,0.5,5.4,2002
6393,A.J. Guyton,PG,24,GSW,2,0,4.5,0.0,2.0,.000,...,0.0,0.0,0.0,1.0,0.5,0.0,0.5,0.0,0.0,2003
14814,A.J. Hammons,C,24,DAL,22,0,7.4,0.8,1.9,.405,...,0.4,1.3,1.6,0.2,0.0,0.6,0.5,1.0,2.2,2017
10727,A.J. Price,PG,23,IND,56,2,15.4,2.6,6.3,.410,...,0.2,1.4,1.6,1.9,0.6,0.1,1.1,0.9,7.3,2010
11356,A.J. Price,PG,24,IND,50,0,15.9,2.3,6.4,.356,...,0.3,1.1,1.4,2.2,0.6,0.0,1.1,1.2,6.5,2011

In [44]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
467,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1412,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1911,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2381,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2948,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3541,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [49]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [50]:
combined.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN

In [51]:
combined[combined["Pts Won"] > 0]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
8055,Kenny Smith,PG,25,HOU,78,78,34.6,6.7,12.9,.520,...,7.1,1.4,0.1,3.0,1.7,17.7,1991,5.0,960.0,0.005
8056,Kenny Smith,PG,26,HOU,81,80,33.8,5.3,11.2,.475,...,6.9,1.3,0.1,2.8,1.4,14.0,1992,5.0,960.0,0.005
8057,Kenny Smith,PG,27,HOU,82,82,29.5,4.7,9.1,.520,...,5.4,1.0,0.1,2.0,1.3,13.0,1993,5.0,960.0,0.005
8058,Kenny Smith,PG,28,HOU,78,78,28.3,4.4,9.1,.480,...,4.2,0.8,0.1,1.6,1.6,11.6,1994,5.0,960.0,0.005
8059,Kenny Smith,PG,29,HOU,81,81,25.1,3.5,7.3,.484,...,4.0,0.9,0.1,1.5,1.3,10.4,1995,5.0,960.0,0.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15303,Bernard King,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,7.0,960.0,0.007
15304,Kenny Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,5.0,960.0,0.005
15305,Hakeem Olajuwon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,4.0,960.0,0.004
15306,Tim Hardaway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,1.0,960.0,0.001
15307,Kevin McHale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,1.0,960.0,0.001

In [58]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [61]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0,0,0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0,0,0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0,0,0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0,0,0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15303,Bernard King,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,0,0,0
15304,Kenny Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,0,0,0
15305,Hakeem Olajuwon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,0,0,0
15306,Tim Hardaway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,0,0,0
15307,Kevin McHale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,0,0,0

In [77]:
teams = pd.read_csv("team.csv")

In [78]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,â€”,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1063,13,56,26,.683,â€”,115.6,109.9,5.37,2022,Memphis Grizzlies*
1064,14,52,30,.634,4.0,108.0,104.7,3.12,2022,Dallas Mavericks*
1065,15,36,46,.439,20.0,109.3,110.3,-0.84,2022,New Orleans Pelicans*
1066,16,34,48,.415,22.0,113.2,113.0,0.02,2022,San Antonio Spurs
1067,17,20,62,.244,36.0,109.7,118.2,-8.26,2022,Houston Rockets

In [79]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,â€”,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,â€”,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
14,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
15,1,55,27,.671,â€”,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
22,8,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1991,Pacific Division
23,9,63,19,.768,â€”,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings

In [82]:
teams = teams[~teams["W"].str.contains("Division")]

In [84]:
teams["Team"] = teams["Team"].str.replace("*", "", regex = False)

In [85]:
teams.head(5)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,â€”,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets

In [86]:
teams["Team"].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [87]:
combined["Tm"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'CHI', 'GSW', 'IND',
       'WAS', 'MIN', 'BOS', 'HOU', 'DEN', 'ORL', 'NOH', 'TOR', 'SAC',
       'CHO', 'PHI', 'POR', 'DET', 'OKC', 'UTA', 'MIL', 'VAN', 'SEA',
       'NJN', 'NOK', 'LAC', 'ATL', 'CHA', 'MEM', 'NYK', 'NOP', 'BRK',
       'SAS', 'CHH', nan], dtype=object)

In [115]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [118]:
combined["Team"] = combined["Tm"].map(nicknames)

In [120]:
combined.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0,0,0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0,0,0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0,0,0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0,0,0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0,0,0,Phoenix Suns

In [121]:
stats = combined.merge(teams, how="outer", on=["Team", "Year"])

In [122]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy*,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,Los Angeles Lakers,10.0,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Charlotte Hornets,14.0,36,46,.439,8.0,108.2,108.0,0.07
15347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Charlotte Hornets,13.0,39,43,.476,3.0,110.7,111.8,-1.32
15348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Charlotte Hornets,14.0,23,42,.354,17.0,102.9,109.6,-7.03
15349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Charlotte Hornets,15.0,33,39,.458,8.0,109.5,111.4,-1.94
15350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Charlotte Hornets,14.0,43,39,.524,10.0,115.3,114.9,0.53

In [123]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0,0,0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0,0,0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0,0,0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0,0,0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0,0,0,Phoenix Suns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15303,Bernard King,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,0,0,0,NaN
15304,Kenny Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,0,0,0,NaN
15305,Hakeem Olajuwon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,0,0,0,NaN
15306,Tim Hardaway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,0,0,0,NaN
15307,Kevin McHale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,0,0,0,NaN

In [ ]:
del stat["un"]